{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "397c7fa4-91b4-4b98-8f1d-82d6d93bb71b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "--- Scientific Calculator Running ---\n",
      "Addition (10, 20): 30\n",
      "Power (2^3): 8.0\n",
      "Square Root (16): 4.0\n",
      "[Error]: Cannot divide by zero.\n",
      "Zero Division Test: None\n",
      "History Stack: [('add(10, 20)', 30), ('power(2, 3)', 8.0), ('sqrt(16,)', 4.0)]\n"
     ]
    }
   ],
   "source": [
    "import math\n",
    "\n",
    "class ScientificCalculator:\n",
    "    def __init__(self):\n",
    "        # Memory stack for undo/history feature\n",
    "        self.history = []\n",
    "\n",
    "    def push_history(self, expression: str, result: float):\n",
    "        \"\"\"Adds calculation to memory stack.\"\"\"\n",
    "        self.history.append((expression, result))\n",
    "\n",
    "    def calculate(self, operation: str, *args) -> float:\n",
    "        \"\"\"Executes basic and scientific operations with defensive handling.\"\"\"\n",
    "        try:\n",
    "            if operation == 'add':\n",
    "                res = sum(args)\n",
    "            elif operation == 'subtract':\n",
    "                res = args[0] - sum(args[1:])\n",
    "            elif operation == 'multiply':\n",
    "                res = 1\n",
    "                for val in args:\n",
    "                    res *= val\n",
    "            elif operation == 'divide':\n",
    "                if 0 in args[1:]:\n",
    "                    raise ZeroDivisionError(\"Cannot divide by zero.\")\n",
    "                res = args[0]\n",
    "                for val in args[1:]:\n",
    "                    res /= val\n",
    "            elif operation == 'power':\n",
    "                res = math.pow(args[0], args[1])\n",
    "            elif operation == 'sqrt':\n",
    "                if args[0] < 0:\n",
    "                    raise ValueError(\"Cannot calculate square root of a negative number.\")\n",
    "                res = math.sqrt(args[0])\n",
    "            elif operation == 'log':\n",
    "                if args[0] <= 0:\n",
    "                    raise ValueError(\"Logarithm undefined for non-positive numbers.\")\n",
    "                res = math.log10(args[0])\n",
    "            else:\n",
    "                raise ValueError(\"Unsupported operation.\")\n",
    "\n",
    "            expr_str = f\"{operation}{args}\"\n",
    "            self.push_history(expr_str, res)\n",
    "            return res\n",
    "\n",
    "        except ZeroDivisionError as e:\n",
    "            print(f\"[Error]: {e}\")\n",
    "            return None\n",
    "        except ValueError as e:\n",
    "            print(f\"[Error]: {e}\")\n",
    "            return None\n",
    "        except Exception as e:\n",
    "            print(f\"[Unexpected Error]: {e}\")\n",
    "            return None\n",
    "\n",
    "    def undo_last():\n",
    "        \"\"\"Pops the last operation from memory stack.\"\"\"\n",
    "        if self.history:\n",
    "            return self.history.pop()\n",
    "        print(\"[Info]: Memory stack is empty.\")\n",
    "        return None\n",
    "\n",
    "\n",
    "# Driver Code / CLI Run\n",
    "if __name__ == \"__main__\":\n",
    "    calc = ScientificCalculator()\n",
    "\n",
    "    print(\"--- Scientific Calculator Running ---\")\n",
    "    print(\"Addition (10, 20):\", calc.calculate('add', 10, 20))\n",
    "    print(\"Power (2^3):\", calc.calculate('power', 2, 3))\n",
    "    print(\"Square Root (16):\", calc.calculate('sqrt', 16))\n",
    "    print(\"Zero Division Test:\", calc.calculate('divide', 10, 0)) # Error handled defensively\n",
    "    print(\"History Stack:\", calc.history)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "53605992-b018-498c-8009-b82877ff825b",
   "metadata": {},
   "outputs": [],
   "source": [
    "#import math"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fabc17d9-1127-48fd-a8a2-eb11ecda353c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "---SMART SCIENTIFIC CALCULATOR---\n",
      "1. Addition (+)\n",
      "2. Subtraction (-)\n",
      "3. Multiplication(*)\n",
      "4. Division (/)\n",
      "5. Square root (√)\n",
      "6. Logarithm (log10)\n",
      "7. Percentage(%)\n",
      "8. Exit\n"
     ]
    }
   ],
   "source": [
    "while True:\n",
    "         print(\"\\n---SMART SCIENTIFIC CALCULATOR---\")\n",
    "         print(\"1. Addition (+)\")\n",
    "         print(\"2. Subtraction (-)\")\n",
    "         print(\"3. Multiplication(*)\")\n",
    "         print(\"4. Division (/)\")\n",
    "         print(\"5. Square root (√)\")\n",
    "         print(\"6. Logarithm (log10)\")\n",
    "         print(\"7. Percentage(%)\")\n",
    "         print(\"8. Exit\")\n",
    "         choice = input(\"option select karo(1/2/3/4/5/6/7/8): \")\n",
    "         if choice ==\"8\":\n",
    "          print(\" CALCULATOR OFF HO GAYA. BYE BYE!\")\n",
    "          break\n",
    "         elif choice ==\"1\":\n",
    "              num1 =float(input(\"First number:\"))\n",
    "              num2 =float(input(\"Second number:\"))\n",
    "              print(\"Result:\", num1+num2)\n",
    "         elif choice ==\"2\":\n",
    "              num1 =float(input(\"First number:\"))\n",
    "              num2 =float(input(\"Second number:\"))\n",
    "              print(\"Result:\", num1-num2)\n",
    "         elif choice ==\"3\":\n",
    "              num1 =float(input(\"First number:\"))\n",
    "              num2 =float(input(\"Second number:\"))\n",
    "              print(\"Result:\", num1*num2)\n",
    "         elif choice ==\"4\":\n",
    "              num1 =float(input(\"First number:\"))\n",
    "              num2 =float(input(\"Second number:\"))\n",
    "              if num2 ==0:\n",
    "                print(\"Error:Zero(0) se divide nahi ho sakta!\")\n",
    "              else:\n",
    "                 print(\"Result:\",num1/num2)\n",
    "         elif choice ==\"5\":\n",
    "            num1 = float(input(\"Number:\"))\n",
    "            if num1 < 0:\n",
    "               print(\"Error:Negative number ka squareroot nhi hota!\")\n",
    "            else:\n",
    "                 print(\"Result:\",math.sqrt(num1))\n",
    "         elif choice==\"6\":\n",
    "             num1= float(input(\"Number: \"))\n",
    "             if num1 <=0:\n",
    "                 print(\"Error: Logarithm non-positive numbers ke liye nahi  hota hai!\")\n",
    "             else:    \n",
    "                 print(\"Result:\", math.log10(num1))\n",
    "         elif choice ==\"7\":\n",
    "              total =float(input(\"Total amount/value:\"))\n",
    "              percent =float(input(\"Percentage(%):\"))\n",
    "              print(\"Result:\",(total*percent) /100)\n",
    "                     \n",
    "         else:\n",
    "          print(\"Invalid choice! kripaya 1 se 8 tak select karo\")               \n",
    "\n",
    "\n",
    "\n",
    "\n",
    "         \n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "        \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cedde163-fb9a-4090-a2db-d326c282b917",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e8c1126a-8b59-4572-9f20-d7e5349512a8",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "40d8756d-638c-4fd7-92e1-e76b7f83a85c",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4e31bdea-6dff-425e-b4e7-56eac7e8733c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
